export var quotes = [["Convince yourself that you have the power to be all what you wish to be. It is YOU who could generate in you a huge power of motivation to push you forward and ignite you to think and to do.",
"—Unknown"],
["You can’t go back and change the beginning, but you can start where you are and change the ending.",
"—C. S. Lewis"],
["Happiness is not the absence of problems, it’s the ability to deal with them.",
"—Steve Maraboli"],
["The most precious gift we can offer others is our presence. When our mindfulness embraces those we love, they will bloom like flowers.",
"—Thich Nhat Hanh"],
["Miracles start to happen when you give as much energy to your dreams as you do to your fears.",
"—Richard Wilkins"],
["If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
"—Zig Ziglar"],
["Don’t be upset with people and situations in your life, because both are powerless without your reaction.",
"—Unknown"],
["Be patient. Empires are not built in a day",
"—Unknown"],
["Never perceive anything as being inevitable or predestined. The only absolute is uncertainty.",
"—Lionel Suggs"],
["Love is a fruit in season at all times and within reach of every hand.",
"—Mother Terea"],
["The truest indication of gratitude is to return what you are grateful for.",
"—Richard Paul Evans"],
["There’s no need to rush. What’s meant for you always arrives right on time.",
"—Unknown"],
["Happiness lies in the joy of achievement and the thrill of creative effort.",
"—Franklin D. Roosevelt"],
["The very purpose of our life is to seek happiness.",
"—Dalai Lama"],
["Find the sweetness in your own heart so that you may find the sweetness in every Heart!",
"—Rumi"],
["Open your eyes to the beauty around you, Open your mind to the wonders of life, Open your heart to those who love you, And always be true to yourself.",
"—Maya Angelou"],
["For everything you have lost, you have gained something else.",
"—Unknown"],
["A failure establishes only this, that our determination to succeed was not strong enough.",
"—John Christian Bovee"],
["Doing what you like is freedom. Liking what you do is happiness.",
"—Frank Tyger"],
["The universe will often give you what you truly desire, even when you didn’t realize it was what you were truly wanting.",
"—Unknown"],
["We have a ‘strategic’ plan. It’s called doing things.",
"—Herb Kelleher"],
["Your future is created by what you do today, not tomorrow.",
"—Unknown"],
["The happiest people don’t have the best of everything, they make the best of everything.",
"—Unknown"],
["In life, you’ll meet two kinds of people. The ones who build you up and the ones who tear you down. In the end, you’ll thank them both.",
"—Unknown"],
["I thank all those who laughed at my dreams; you taught me to grow respecting other people’s struggles",
"—Paulo Coelho"],
["For, as almost every extraordinary life shows, there is a vision, an ideal that calls.",
"—James Hillman"],
["Always stay true to yourself and never sacrifice who you are for anyone.",
"—Unknown"],
["You can’t change what’s going on around you until you start changing what’s going on within you.",
"—Unknown"],
["The price of inaction is far greater than the cost of making a mistake.",
"—Meister Eckhart"],
["Never give anyone the power to take away your joy.",
"—Jeanette Jenkins"],
["Love is like the wind. You can’t see it, but you can feel it.",
"—Nicholas Sparks."],
["If you paint in your mind a picture of bright and happy expectations, you put yourself into a condition conducive to your goals.",
"—Norman Vincent Peale"],
["Don’t be scared to walk alone. Don’t be scared to like it.",
"—John Mayer"],
["To be a champ, you have to believe in yourself when nobody else will.",
"—Sugar Ray Robinson"],
["Nobody is superior, nobody is inferior, but nobody is equal either. People are simply unique, incomparable.",
"—Osho"],
["Life becomes lighter when we focus on reality and presentments rather than abstract ideas and interpretations",
"—Unknown"],
["Some people feel the rain. Others just get wet.",
"—Bob Marley"],
["Good things come to those who go get them.",
"—Unknown"],
["You are searching the world for treasure, but the real treasure is Yourself.",
"—Rumi"],
["The greatest mistake we make is living in constant fear that we will make one.",
"—Unknown"],
["If you think you can win, you can win. Faith is necessary to victory.",
"—William Hazlitt"],
["You are the universe, expressing itself as a human for a little while.",
"—Eckhart Tolle"],
["To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
"—Ralph Waldo Emerson"],
["Love is the big booming beat which covers up the noise of hate.",
"—Margaret Cho"],
["When you find peace within yourself, you become the kind of person who can live at peace with others.",
"—Peace Pilgrim"],
["The Universe is not punishing you or blessing you. The Universe is responding to the vibrational attitude that you are emitting.",
"—LOA"],
["Once you carry your own water, you will learn the value of every drop.",
"—Unknown"],
["Don’t compare yourself to others. Keep playing the competitive game between you and you.",
"—Unknown"],
["He who lives in harmony with himself lives in harmony with the universe.",
"—Marcus Aurelius"],
["We should all start to live before we get too old. Fear is stupid. So are regrets.",
"—Marilyn Monroe"],
["I cannot do all the good that the world needs. But the world needs all the good that I can do.",
"—J. Stanfield"],
["Don’t chase people. Be you, do your own thing and work hard. The right people who belong in your life will come to you, and stay.",
"—Unknown"],
["The great man is he who does not lose his child’s-heart.",
"—Mencius"],
["He who lives in harmony with himself lives in harmony with the universe.",
"—Marcus Aurelius"],
["Life is what happens while you are busy making other plans.",
"—John Lennon"],
["What you become is the result of what you do today. In other words, you are preparing for something.",
"—John C. Maxwell"],
["Be who you are and say what you feel because those who mind don’t matter and those who matter don’t mind.",
"—Dr Seuss"],
["How people treat you is their karma; how you react is yours.",
"—Wayne W. Dyer"],
["Good things come to those who believe, better things come to those who are patient, and the best things come to those who don’t give up.",
"—Unknown"],
["Gratitude can transform common days into thanksgivings, turn routine jobs into joy, & change ordinary opportunities into blessings.",
"—Unknown"],
["I have found that if you love life, life will love you back.",
"—The Secret"],
["Men are not prisoners of fate, but prisoners of their own minds.",
"—Franklin D. Roosevelt"],
["People rarely succeed unless they have fun in what they are doing.",
"—Dale Carnegie"],
["The Universe has a plan for you, and it’s Good.",
"—Russell Kyle"],
["Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
"—Christian D. Larson"],
["You don’t have to be great to get started, but you have to get started to be great.",
"—Les Brown"],
["When we strive to become better than we are, everything around us becomes better, too.",
"—Paulo Coelho"],
["The person who says it cannot be done should not interrupt the person doing it.",
"—Chines Proverb"],
["Be the writer of your life and reader of your mind. The more you know yourself the less you need approval of others.",
"—Unknown"],
["Don’t ever give up on what makes you truly happy.",
"—Jonathan Landsman"],
["Healing always involves facing truths we’d rather not face, and accepting responsibility we’d rather not accept.",
"—Dr. David Hawkins"],
["Most people find change difficult to accept, sometimes for good reasons, sometimes because of plain old inertia.",
"—Andrew Hunt"],
["Happiness is not the absence of problems, it’s the ability to deal with them.",
"— Steve Maraboli"],
["An investment in knowledge always pays the best interest.",
"—Benjamin Franklin"],
["There is one technique that you must use if you want people to listen to you: listen to them.",
"—Andrew Hunt"],
["Attitude is a choice. Think positive thoughts daily. Believe in yourself.",
"—Pat Summitt"],
["Leadership is not for everyone. Leadership is a lifestyle, not a position. Leadership is about those you lead, not who is leading.",
"—Greg White"],
["The minute you get away from fundamentals – proper technique, work ethic or mental prep – the bottom can fall out of your game.",
"—Michael Jordan"],
["Never give up! Failure and rejection are only the first step to succeeding.",
"—Jim Valvano"],
["If you want help, help others. If you want love, give it. If you want respect, show it. Whatever you want more of, start giving more of.",
"—Unknown"],
["A dream is your creative vision for your life in the future.",
"—Denis Waitley"],
["Can you remember who you were, before the world told you who you should be?",
"—Charles Bukowski"],
["Tell everyone what you want to do and someone will want to help you do it.",
"—W. Clement Stone"],
["Learn to say ‘no’ to the good so you can say ‘yes’ to the best.",
"—John C. Maxwell"],
["The world is full of magic things, patiently waiting for our senses to grow sharper.",
"—W.B. Yeats"],
["Magic is believing in yourself, if you can do that, you can make anything happen.",
"—Johann Wolfgang von Goethe"],
["We have to do the best we are capable of. This is our sacred human responsibility.",
"—Albert Einstein"],
["When you have confidence, you can have a lot of fun. And when you have fun, you can do amazing things.",
"—Joe Namath"],
["Great things never came from comfort zones.",
"—Neil Strauss"],
["You can turn your life into paradise, but the only way you can do it is to make the inside of you a paradise.",
"—LOA"],
["The first to apologize is the bravest. The first to forgive is the strongest. The first to forget is the happiest.",
"—Unknown"],
["Don’t worry about failures, worry about the chances you miss when you don’t even try.",
"—Jack Canfield"],
["Always bear in mind that your own resolution to succeed is more important than any other one thing.",
"—Abraham Lincoln"],
["Your time is limited, so don’t waste it living someone else’s life.",
"— Steve Jobs"],
["The past has no power over the present moment.",
"—Eckhart Tolle"],
["If you want something you never had, you have to do something you’ve never done.",
"—Thomas Jefferson"],
["Luck is a dividend of sweat. The more you sweat, the luckier you get.",
"—Ray Kroc"],
["If you can change your mind, you can change your life.",
"—William James"],
["It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
"—Charles Darwin"],
["It takes as much energy to wish as it does to plan.",
"—Eleanor Roosevelt"],
["The greatest crime in the world is not developing your potential. When you do what you do best, you are helping not only yourself but the world.",
"—Roger Williams"],
["Once you replace negative thoughts with positive ones, you’ll start having positive results.",
"—Willie Nelson"],
["Education is the key to unlock the golden door of freedom.",
"—George Washington Carve"],
["It’s not your job to like me, it’s mine.",
"—Byron Katie"],
["Create in you the power of self-confidence and self-determination to think and to create the life you love and the success you want.",
"—Unknown﻿"],
["We must never be afraid to go too far, for success lies just beyond.",
"—Marcel Proust"],
["Embrace what you don’t know, especially in the beginning, because what you don’t know can become your greatest asset. It ensures that you will absolutely be doing things different from everybody else.",
"—Sara Blakely"],
["We are what we repeatedly do. Excellence, then, is not an act but a habit.",
"—Aristotle"],
["Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.",
"—Martin Luther King Jr."],
["Education is the key to unlock the golden door of freedom.",
"—George Washington Carve"],
["En la vida algunas veces se gana, otras veces se aprende.",
"—John Maxwell"],
["Don’t give up on yourself. There’s a reason why you started.",
"— Unknown"],
["Happiness comes from WHAT we do. Fulfillment comes from WHY we do it.",
"—Simon Sinek"],
["Build your own dreams, or someone else will hire you to build theirs.",
"—Farrah Gray"],
["The limits of the possible can only be defined by going beyond them into the impossible.",
"—Arthur C. Clarke"],
["All we have is what we do right now. That’s all we’ll ever have. Life is a series of moments. And if you show up authentically in more and more moments, you start to patch together a beautiful life.",
"—Unknown"],
["A good traveler has no fixed plans, and is not intent on arriving.",
"—Lao Tzu"],
["I don’t know what your destiny will be, but one thing I know: The only ones among you who will be truly happy are those who have sought and found how to serve.",
"—Albert Schweitzer"],
["Build something 100 people love, not something one million people kind of like.",
"—Brian Chesky"],
["Tough times never last, but tough people do.",
"—Dr. Robert Schuller"],
["Take chances, make mistakes. That’s how you grow. Pain nourishes your courage. You have to fail in order to practice being brave.",
"—Mary Tyler Moore"],
["Do not indulge in dreams of having what you have not, but reckon up the chief of the blessings you do possess, and then thankfully remember how you would crave for them if they were not yours.",
"—Marcus Aurelius"],
["Everything you’ve ever wanted is on the other side of fear.",
"—George Addair"],
["Success is walking from failure to failure with no loss of enthusiasm.",
"—Winston Churchil"],
["Always make a total effort, even when the odds are against you.",
"—Arnold Palmer"],
["Every moment and every event of every man’s life on earth plants something in his soul.",
"—Thomas Merton"],
["Always forgive your enemies. Nothing annoys them more.",
"—Oscar Wilde"],
["Start making your own happiness a priority.",
"—LOA"],
["I have not failed. I’ve just found 10,000 ways that won’t work.",
"—Thomas Edison"],
["Try to be a rainbow in someone’s cloud.",
"—Maya Angelou"],
["Conditions are never perfect. ‘Someday’ is a disease that will take your dreams to the grave with you…. If it’s important to you and you want to do it ‘eventually,’ just do it and correct course along the way.",
"—Tim Ferriss"],
["Life is what you make of it.",
"—Unknown"],
["Be happy now. Feel good now. That’s the only thing you have to do.",
"—Unknown"]]